//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTable
    {
        public int CustomerID { get; set; }
        public int TableID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime ExpiredTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Table Table { get; set; }
    }
}
